name: Build React App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.7.1

      - name: Install dependencies
        working-directory: ./client
        run: npm install

      - name: Build app
        working-directory: ./client
        run: npm run build

      - name: Upload production-ready build
        uses: actions/upload-artifact@v4
        with:
          name: client-dist
          path: client/dist
